services:
  - type: web
    name: wanderlust-recommendations
    env: python
    rootDir: recommendation
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: wanderlust
      - key: MERN_BACKEND_URL
        sync: false